apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simplecluster
  region: ap-southeast-1

nodeGroups:
- name: ng-small
  kubeletExtraConfig:
    clusterDNS: ["169.254.20.10", "172.20.0.10"]
  instanceType: m5.large
  desiredCapacity: 1

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
