apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simplecluster
  region: ap-southeast-1

iam:
  withOIDC: true

addons:
- name: vpc-cni
  attachPolicyARNs:
  - arn:aws:iam::account:policy/AmazonEKS_CNI_Policy
  attachPolicy:
    Statement:
    - Effect: Allow
      Action:
      - ec2:AssignPrivateIpAddresses
      - ec2:AttachNetworkInterface
      - ec2:CreateNetworkInterface
      - ec2:DeleteNetworkInterface
      - ec2:DescribeInstances
      - ec2:DescribeTags
      - ec2:DescribeNetworkInterfaces
      - ec2:DescribeInstanceTypes
      - ec2:DetachNetworkInterface
      - ec2:ModifyNetworkInterfaceAttribute
      - ec2:UnassignPrivateIpAddresses
      Resource: '*'

managedNodeGroups:
- name: ng-small
  kubeletExtraConfig:
    clusterDNS: ["169.254.20.10", "172.20.0.10"]
  instanceType: m5.large
  spot: true
  minSize: 2
  maxSize: 5
  desiredCapacity: 2
  amiFamily: Bottlerocket
  bottlerocket:
    enableAdminContainer: true
  labels: {type: spot}

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
