apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simplecluster
  region: ap-southeast-1

addons:



managedNodeGroups:
- name: ng-small
  kubeletExtraConfig:
    clusterDNS: ["169.254.20.10", "172.20.0.10"]
  instanceType: m5.large
  spot: true
  minSize: 2
  maxSize: 5
  desiredCapacity: 2
  amiFamily: Bottlerocket
  bottlerocket:
    enableAdminContainer: true
  labels: {type: spot}

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
